### ISSUE TITLE
Higurashi Rei DLL TODO

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-assembly#74]
Work on the Higurashi Rei Modded DLL is being done on this branch: https://github.com/07th-mod/higurashi-assembly/tree/rei-mod-ALPHA

To see the original code, see the corresponding rei-mg-ALPHA and rei-steam-ALPHA branches

# Known Bugs

## ~~Bugs related to `sharedassets` needing to be updated~~

- ~~[ ] Config menu sliders have wrong names next to them~~
- ~~[ ] Old UI and fonts are used~~

~~Need to compile new sharedassets: https://github.com/07th-mod/ui-editing-scripts~~

Sharedassets status/problems here: https://github.com/07th-mod/higurashi-rei/issues/1

~~## Game sometimes freezes for a couple seconds the first time you open the mod menu or main menu "config" screen~~

~~I think this is due to the mod menu. There seems to be some work that is done the first time the mod menu is opened. The same work happens the first time you open the config screen, probably due to the little button on the lower left that I added which lets you open the mod menu from the config screen.~~

This has been moved to https://github.com/07th-mod/higurashi-rei/issues/2

----

## Misc Notes

- If your textbox background doesn't work, you're missing the textbox image files `windo_filter.png`, `windo_filter_adv.png`, `windo_filter_adv.png`, which are normally in the `StreamingAssets/CG` folder.
- If your screen resolution is not 16:9 or you have other graphics issues, makes sure you have the latest `init.txt` (and other scripts) from the [`higurashi-rei` repository](https://github.com/07th-mod/higurashi-rei)

----

## Optional Tasks

- [x] Backport Fix for game crashing on startup with level0 is corrupted error

From GameSystem.cs:
```C
		// Unity will attempt to deserialize public properties and these aren't in the AssetBundle,
		// so use private ones with public accessors
````
I added a variable a while ago called "_MODIgnoreInputs", which caused the Rei engine to crash on startup ( but seemingly not the other chapters). I'm not sure if this causes issues on older chapters, so not sure if it's worth back-porting the fix.

- [x]  Backport this fix to avoid crash if texture missing and filter applied: 84dfefb1ae14aa05f8f71cf18379a436331c280c

---- 

## Fixed bugs

- Bugs related to voices and lipsync (edit: figured it out, pending new DLL release)
  - There seems to be some issue where the game does not wait for voices to finish before continuing, or where voices continue to play where they shouldn't.
  - Autoplay was quite broken, it doesn't consider the length of audio lines, so it'll cut them frequently
  - Voices can ply through scene transitions if you click through (or maybe just always)
- Fixed Sliders on the config menu (not the mod menu) don't work at all
    - [x] Sliders will have the wrong names to them until the sharedassets are updated 
- Remove formatting commands from save/load page text preview
- Nametags don't display properly on text log
- Fix fullscreen not working properly via ALT-ENTER, and fullscreen not saving
- Fix overlapping backlog text
    - [x] I haven't tested whether you can click on the backlog to play back voices yet. 
- Fix movie playback on Linux/MacOS 
    - NOTE: The built-in Unity movie player is now used on all platforms (including Windows). If this causes problems on Windows we can revert back to the AVProVideo player.
    - [x] We will need to test what encoder settings work on Linux, see https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html. I have changed how the player works - there is a list of file extensions depending on the OS, and it will try to find a video file with the correct extension, so you have some flexibility in the file type used.
- Fix character names displaying with a `¥n` symbol and not outputting newlines
- Fix `Select()` calls throwing an exception / not showing anything and stopping you progressing
- The screen resolution is too small on first startup (fixed if you apply updated init.txt)
- You can only right click on title menu buttons to open them, not left click
- Opening or closing the mod menu, or changing mod options while not at the main menu can cause the game to reset or get stuck
- **Not sure if fixed**: Quick Save is inaccessible until you click on another UI option.

**Comment by drojf** [comment]
Closing this issue as most of the issues on Rei are fixed now. Raise individual issues if more problems arise on Rei.
